import { Part } from "@/types/workOrder"

export const partsData: Part[] = [
  // Power Nozzle Group
  { id: "pn-1", group: "Power Nozzle", name: "Cover ASM", partNumber: "T1070", description: "Cover ASM", price: 29.99, quantity: 1 },
  { id: "pn-2", group: "Power Nozzle", name: "Cover Screw", partNumber: "T1071B", description: "Screw, Cover (Bagged 10)", price: 9.99, quantity: 10 },
  { id: "pn-3", group: "Power Nozzle", name: "Motor Screw", partNumber: "T1072B", description: "Screw, Motor (Bagged 10)", price: 9.99, quantity: 10 },
  { id: "pn-4", group: "Power Nozzle", name: "Release Pivot Arm", partNumber: "T1073B", description: "Pivot Arm, Release (Bagged 10)", price: 19.99, quantity: 10 },
  { id: "pn-5", group: "Power Nozzle", name: "Motor Bracket", partNumber: "T1074B", description: "Motor Bracket (Bagged 10)", price: 24.99, quantity: 10 },
  { id: "pn-6", group: "Power Nozzle", name: "Pivot Arm ASM", partNumber: "T1075", description: "Pivot Arm ASM", price: 34.99, quantity: 1 },
  { id: "pn-7", group: "Power Nozzle", name: "Motor and Pulley ASM 120V", partNumber: "T1076", description: "Motor and Pulley ASM 120V", price: 89.99, quantity: 1 },
  { id: "pn-8", group: "Power Nozzle", name: "Upright Lock Screw", partNumber: "T1077B", description: "Screw, Upright Lock (Bagged 10)", price: 9.99, quantity: 10 },
  { id: "pn-9", group: "Power Nozzle", name: "Upright Lock ASM", partNumber: "T1078", description: "Upright Lock ASM", price: 29.99, quantity: 1 },
  { id: "pn-10", group: "Power Nozzle", name: "Air Vent Slide Valve", partNumber: "T1079B", description: "Air Vent Slide Valve (Bagged 10)", price: 14.99, quantity: 10 },
  { id: "pn-11", group: "Power Nozzle", name: "Wire Saddle Clip", partNumber: "T1080B", description: "Wire Saddle Clip (Bagged 5)", price: 7.99, quantity: 5 },
  { id: "pn-12", group: "Power Nozzle", name: "Upright Lock Spring", partNumber: "T1081B", description: "Spring, Upright Lock (Bagged 10)", price: 9.99, quantity: 10 },
  { id: "pn-13", group: "Power Nozzle", name: "Manifold and Wheels ASM", partNumber: "T1082", description: "Manifold and Wheels ASM", price: 49.99, quantity: 1 },
  { id: "pn-14", group: "Power Nozzle", name: "Belt Door", partNumber: "T1083B", description: "Belt Door (Bagged 5)", price: 19.99, quantity: 5 },
  { id: "pn-15", group: "Power Nozzle", name: "LED Headlight ASM", partNumber: "T1084", description: "LED Headlight ASM, 120V", price: 39.99, quantity: 1 },
  { id: "pn-16", group: "Power Nozzle", name: "Sole Plate ASM", partNumber: "T1085", description: "Sole Plate ASM", price: 44.99, quantity: 1 },
  { id: "pn-17", group: "Power Nozzle", name: "Sole Plate Cover ASM", partNumber: "R14327B", description: "Sole Plate Cover ASM", price: 34.99, quantity: 1 },
  { id: "pn-18", group: "Power Nozzle", name: "Brush Roll ASM Medium", partNumber: "T1137C", description: "Brush Roll ASM, Offset, Medium Stiffness", price: 39.99, quantity: 1 },
  { id: "pn-19", group: "Power Nozzle", name: "Brush Roll ASM Medium 2", partNumber: "T1138C", description: "Brush Roll ASM, Offset, Medium Stiffness", price: 39.99, quantity: 1 },
  { id: "pn-20", group: "Power Nozzle", name: "Brush Roll ASM Medium 3", partNumber: "T1139C", description: "Brush Roll ASM, Offset, Medium Stiffness", price: 39.99, quantity: 1 },
  { id: "pn-21", group: "Power Nozzle", name: "Brush Roll ASM Medium 4", partNumber: "T1152C", description: "Brush Roll ASM, Offset, Medium Stiffness", price: 39.99, quantity: 1 },
  { id: "pn-22", group: "Power Nozzle", name: "Brush Roll ASM Medium 5", partNumber: "T1136C", description: "Brush Roll ASM, Offset, Medium Stiffness", price: 39.99, quantity: 1 },
  { id: "pn-23", group: "Power Nozzle", name: "PN Bristle Strip Maroon", partNumber: "T1151B", description: "PN Bristle Strip, Maroon, Medium", price: 14.99, quantity: 1 },
  { id: "pn-24", group: "Power Nozzle", name: "PN Bristle Strip Stiff", partNumber: "T1111B", description: "PN Bristle Strip, Stiff", price: 14.99, quantity: 1 },
  { id: "pn-25", group: "Power Nozzle", name: "PN Bristle Strip Medium", partNumber: "T1127B", description: "PN Bristle Strip, Medium Stiff", price: 14.99, quantity: 1 },
  { id: "pn-26", group: "Power Nozzle", name: "PN Bristle Strip Medium 2", partNumber: "T1128B", description: "PN Bristle Strip, Medium Stiff", price: 14.99, quantity: 1 },
  { id: "pn-27", group: "Power Nozzle", name: "PN Bristle Strip Soft", partNumber: "T1129B", description: "PN Bristle Strip, Soft, SV", price: 14.99, quantity: 1 },
  { id: "pn-28", group: "Power Nozzle", name: "Belt", partNumber: "R15364B", description: "Belt, PN, H-Section, 5-Rib", price: 14.99, quantity: 1 },
  { id: "pn-29", group: "Power Nozzle", name: "Bearing Retainer ASM", partNumber: "T1113B", description: "Bearing Retainer ASM (Bagged 10)", price: 19.99, quantity: 10 },
  { id: "pn-30", group: "Power Nozzle", name: "Brush Roll End Cap", partNumber: "T1114B", description: "Brush Roll End Cap (Bagged 10)", price: 9.99, quantity: 10 },

  // Main Housing Assembly Group
  { id: "mh-1", group: "Main Housing Assembly", name: "Main Housing", partNumber: "T1001", description: "Main Housing", price: 149.99, quantity: 1 },
  { id: "mh-2", group: "Main Housing Assembly", name: "Lift Strut", partNumber: "T1002B", description: "Lift Strut (Bagged 2)", price: 29.99, quantity: 2 },
  { id: "mh-3", group: "Main Housing Assembly", name: "Interlock Switch ASM", partNumber: "T1003", description: "Interlock Switch ASM", price: 34.99, quantity: 1 },
  { id: "mh-4", group: "Main Housing Assembly", name: "Water Pan LED Lens", partNumber: "T1004", description: "Lens, Water Pan LED", price: 19.99, quantity: 1 },
  { id: "mh-5", group: "Main Housing Assembly", name: "Upper Pin Lift Strut", partNumber: "T1005B", description: "Upper Pin, Lift Strut (Bagged 50)", price: 24.99, quantity: 50 },
  { id: "mh-6", group: "Main Housing Assembly", name: "Chin Latch", partNumber: "T1006B", description: "Latch, Chin (Bagged 10)", price: 14.99, quantity: 10 },
  { id: "mh-7", group: "Main Housing Assembly", name: "Lens Panel RH", partNumber: "T1007", description: "Lens Panel, SRX (Clear Blue), RH", price: 29.99, quantity: 1 },
  { id: "mh-8", group: "Main Housing Assembly", name: "Chin Latch Spring", partNumber: "T1008B", description: "Spring, Chin Latch (Bagged 100)", price: 19.99, quantity: 100 },
  { id: "mh-9", group: "Main Housing Assembly", name: "Controller Housing", partNumber: "T1017", description: "Controller w/Housing ASM 120V", price: 89.99, quantity: 1 },
  { id: "mh-10", group: "Main Housing Assembly", name: "Cord ASM", partNumber: "T1010P", description: "Cord ASM", price: 29.99, quantity: 1 },
  { id: "mh-11", group: "Main Housing Assembly", name: "HEPA Filter Bulk", partNumber: "T1011B", description: "HEPA Filter (Bulk PK 54)", price: 299.99, quantity: 54 },
  { id: "mh-12", group: "Main Housing Assembly", name: "HEPA Filter Single", partNumber: "T1189", description: "HEPA Filter", price: 79.99, quantity: 1 },
  { id: "mh-13", group: "Main Housing Assembly", name: "Lens Panel LH", partNumber: "T1012", description: "Lens Panel, SRX (Clear Blue), LH", price: 29.99, quantity: 1 },
  { id: "mh-14", group: "Main Housing Assembly", name: "Exhaust Bellows Kit", partNumber: "T1013K", description: "Exhaust Bellows Kit Replaced by T1013", price: 39.99, quantity: 1 },
  { id: "mh-15", group: "Main Housing Assembly", name: "Bellows Clamp", partNumber: "T1014B", description: "Clamp, Bellows to Housing (Bagged 20)", price: 14.99, quantity: 20 },
  { id: "mh-16", group: "Main Housing Assembly", name: "Chin Latch Pin", partNumber: "T1015B", description: "Pin, Chin Latch (Bagged 100)", price: 9.99, quantity: 100 },
  { id: "mh-17", group: "Main Housing Assembly", name: "Controller Encoder", partNumber: "T1016B", description: "Controller Encoder Harness (Bag 5)", price: 29.99, quantity: 5 },
  { id: "mh-18", group: "Main Housing Assembly", name: "Side Panel LH", partNumber: "T1157B", description: "Side Panel Applique, LH (Bagged 10)", price: 19.99, quantity: 10 },
  { id: "mh-19", group: "Main Housing Assembly", name: "Side Panel RH", partNumber: "T1158B", description: "Side Panel Applique, RH (Bagged 10)", price: 19.99, quantity: 10 },
  { id: "mh-20", group: "Main Housing Assembly", name: "Duct Box/Lid", partNumber: "T1184", description: "Duct Box/Lid ASM 120V, BLK", price: 49.99, quantity: 1 },
  { id: "mh-21", group: "Main Housing Assembly", name: "Heat Sink Spacer", partNumber: "T1185B", description: "Heat Sink Spacer, Bagged (50)", price: 9.99, quantity: 50 },

  // Cap Assembly Group
  { id: "ca-1", group: "Cap Assembly", name: "Top Handle Applique", partNumber: "T1018", description: "Applique, Top Handle", price: 14.99, quantity: 1 },
  { id: "ca-2", group: "Cap Assembly", name: "Handle Pad ASM", partNumber: "T1019", description: "Handle Pad ASM", price: 19.99, quantity: 1 },
  { id: "ca-3", group: "Cap Assembly", name: "Cap Cover ASM", partNumber: "T1020", description: "Cap Cover ASM", price: 39.99, quantity: 1 },
  { id: "ca-4", group: "Cap Assembly", name: "Front Badge Applique", partNumber: "T1021", description: "Applique, Front Badge", price: 9.99, quantity: 1 },
  { id: "ca-5", group: "Cap Assembly", name: "Attachment Caddy", partNumber: "T1022", description: "Attachment Caddy", price: 24.99, quantity: 1 },
  { id: "ca-6", group: "Cap Assembly", name: "Actuator ASM", partNumber: "T1023", description: "Actuator ASM", price: 29.99, quantity: 1 },
  { id: "ca-7", group: "Cap Assembly", name: "Cap Switch ASM", partNumber: "T1024B", description: "Cap Switch ASM (Bagged 10)", price: 34.99, quantity: 10 },
  { id: "ca-8", group: "Cap Assembly", name: "User Interface", partNumber: "T1025", description: "User Interface", price: 49.99, quantity: 1 },
  { id: "ca-9", group: "Cap Assembly", name: "Wedge", partNumber: "T1159B", description: "Wedge (Bagged 50)", price: 9.99, quantity: 50 },
  { id: "ca-10", group: "Cap Assembly", name: "Power Switch ASM", partNumber: "T1186B", description: "Power Switch ASM, SRX (Bagged 5)", price: 29.99, quantity: 5 },

  // Dolly Assembly Group
  { id: "da-1", group: "Dolly Assembly", name: "Lower Baffle Plate", partNumber: "T1026", description: "Baffle Plate, Lower", price: 19.99, quantity: 1 },
  { id: "da-2", group: "Dolly Assembly", name: "Separator Brush", partNumber: "T1116B", description: "Separator Brush (Bagged 10)", price: 14.99, quantity: 10 },
  { id: "da-3", group: "Dolly Assembly", name: "Housing Screw", partNumber: "T1027B", description: "Screw, Housing (Bagged 100)", price: 9.99, quantity: 100 },
  { id: "da-4", group: "Dolly Assembly", name: "Hinge Pin Cap RH", partNumber: "T1028B", description: "Cap, Hinge Pin, RH (Bagged 10)", price: 7.99, quantity: 10 },
  { id: "da-5", group: "Dolly Assembly", name: "Waterpan ASM", partNumber: "T1029", description: "Waterpan ASM", price: 39.99, quantity: 1 },
  { id: "da-6", group: "Dolly Assembly", name: "Hinge Axle", partNumber: "T1030B", description: "Hinge Axle (Bagged 10)", price: 12.99, quantity: 10 },
  { id: "da-7", group: "Dolly Assembly", name: "Hinge Pin Cap LH", partNumber: "T1031B", description: "Cap, Hinge Pin, LH (Bagged 10)", price: 7.99, quantity: 10 },
  { id: "da-8", group: "Dolly Assembly", name: "Dolly ASM", partNumber: "T1201", description: "Dolly ASM, Service, SRX", price: 79.99, quantity: 1 },

  // Rear Cover Assembly Group
  { id: "rc-1", group: "Rear Cover Assembly", name: "Cord Wrap Slide", partNumber: "T1035", description: "Cord Wrap, Slide", price: 14.99, quantity: 1 },
  { id: "rc-2", group: "Rear Cover Assembly", name: "Cord Wrap Spring", partNumber: "T1036B", description: "Spring, Cord Wrap Slide (Bagged 50)", price: 9.99, quantity: 50 },
  { id: "rc-3", group: "Rear Cover Assembly", name: "Vent Door", partNumber: "T1037", description: "Vent Door, Rear Cover", price: 19.99, quantity: 1 },
  { id: "rc-4", group: "Rear Cover Assembly", name: "Rear Cover ASM", partNumber: "T1038", description: "Rear Cover ASM", price: 49.99, quantity: 1 },
  { id: "rc-5", group: "Rear Cover Assembly", name: "Housing Screw", partNumber: "T1027B", description: "Screw, Housing (Bagged 100)", price: 9.99, quantity: 100 },

  // Faceplate Assembly Group
  { id: "fp-1", group: "Faceplate Assembly", name: "Face Plate Door Spring", partNumber: "T1040B", description: "Spring, Face Plate Door (Bagged 50)", price: 9.99, quantity: 50 },
  { id: "fp-2", group: "Faceplate Assembly", name: "Face Plate Door", partNumber: "T1041", description: "Face Plate Door", price: 24.99, quantity: 1 },
  { id: "fp-3", group: "Faceplate Assembly", name: "Face Plate Neck Duct", partNumber: "T1042", description: "Face Plate Neck Duct ASM", price: 34.99, quantity: 1 },
  { id: "fp-4", group: "Faceplate Assembly", name: "Retainer", partNumber: "T1090B", description: "Retainer (Bagged 10)", price: 12.99, quantity: 10 },
  { id: "fp-5", group: "Faceplate Assembly", name: "Face Plate Harness", partNumber: "T1091B", description: "Face Plate Wire Harness ASM (Bag 5)", price: 29.99, quantity: 5 },
  { id: "fp-6", group: "Faceplate Assembly", name: "Screw", partNumber: "H571B", description: "Screw (Bagged 100)", price: 7.99, quantity: 100 },
  { id: "fp-7", group: "Faceplate Assembly", name: "Magnet Receiver", partNumber: "T1099B", description: "Coupling, Magnet Receiver (Bagged 20)", price: 19.99, quantity: 20 },
  { id: "fp-8", group: "Faceplate Assembly", name: "Face Plate Sub-ASM", partNumber: "T1147", description: "Face Plate Sub-ASM", price: 44.99, quantity: 1 },
  { id: "fp-9", group: "Faceplate Assembly", name: "Airflow Adapter", partNumber: "T1155", description: "Airflow Adapter", price: 19.99, quantity: 1 },

  // Motor Assembly Group
  { id: "ma-1", group: "Motor Assembly", name: "Bucket", partNumber: "T1043", description: "Bucket", price: 49.99, quantity: 1 },
  { id: "ma-2", group: "Motor Assembly", name: "Rope Seal", partNumber: "T1044", description: "Rope Seal", price: 9.99, quantity: 1 },
  { id: "ma-3", group: "Motor Assembly", name: "Motor Housing Can", partNumber: "T1045", description: "Can, Motor Housing", price: 39.99, quantity: 1 },
  { id: "ma-4", group: "Motor Assembly", name: "Bearing Spring", partNumber: "T1046B", description: "Spring, Bearing (Bagged 20)", price: 14.99, quantity: 20 },
  { id: "ma-5", group: "Motor Assembly", name: "Rotor ASM", partNumber: "T1047", description: "Rotor ASM", price: 89.99, quantity: 1 },
  { id: "ma-6", group: "Motor Assembly", name: "Stator ASM", partNumber: "T1048", description: "Stator ASM", price: 99.99, quantity: 1 },
  { id: "ma-7", group: "Motor Assembly", name: "Stator Insulator", partNumber: "T1049B", description: "Stator Insulator (Bagged 20)", price: 19.99, quantity: 20 },
  { id: "ma-8", group: "Motor Assembly", name: "Wire Exit Seal", partNumber: "T1050", description: "Seal, Wire Exit", price: 9.99, quantity: 1 },
  { id: "ma-9", group: "Motor Assembly", name: "Bearing Bracket ASM", partNumber: "T1051", description: "Bearing Bracket ASM", price: 34.99, quantity: 1 },
  { id: "ma-10", group: "Motor Assembly", name: "Bearing Bracket Screw", partNumber: "T1052B", description: "Screw, Bearing Bracket (Bagged 50)", price: 9.99, quantity: 50 },
  { id: "ma-11", group: "Motor Assembly", name: "Fan Spacer Short", partNumber: "T1053B", description: "Spacer, Fan, Short (Bagged 20)", price: 7.99, quantity: 20 },
  { id: "ma-12", group: "Motor Assembly", name: "Fan Motor ASM", partNumber: "T1054B", description: "Fan Motor ASM (Bagged 10)", price: 49.99, quantity: 10 },
  { id: "ma-13", group: "Motor Assembly", name: "Fan Spacer Long", partNumber: "T1055B", description: "Spacer, Fan, Long (Bagged 20)", price: 7.99, quantity: 20 },
  { id: "ma-14", group: "Motor Assembly", name: "Stage Nut", partNumber: "T1056B", description: "Stage Nut (Bagged 20)", price: 12.99, quantity: 20 },
  { id: "ma-15", group: "Motor Assembly", name: "Fan Cover ASM", partNumber: "T1057", description: "Fan Cover ASM", price: 29.99, quantity: 1 },
  { id: "ma-16", group: "Motor Assembly", name: "Bucket Screw", partNumber: "T1058B", description: "Screw, Bucket (Bagged 100)", price: 9.99, quantity: 100 },
  { id: "ma-17", group: "Motor Assembly", name: "Bearing Nut", partNumber: "T1089B", description: "Bearing Nut (Bagged 20)", price: 14.99, quantity: 20 },
  { id: "ma-18", group: "Motor Assembly", name: "Bearing ASM", partNumber: "T1088B", description: "Bearing ASM (Bagged 10)", price: 29.99, quantity: 10 },
  { id: "ma-19", group: "Motor Assembly", name: "Separator", partNumber: "T1100", description: "Separator", price: 39.99, quantity: 1 },
  { id: "ma-20", group: "Motor Assembly", name: "Separator Nut", partNumber: "T1101B", description: "Separator Nut (Bagged 20)", price: 12.99, quantity: 20 },
  { id: "ma-21", group: "Motor Assembly", name: "Bearing Bracket Spring", partNumber: "T1142B", description: "Bearing Bracket Spring (Bagged 20)", price: 14.99, quantity: 20 },
  { id: "ma-22", group: "Motor Assembly", name: "Motor Mount Gasket", partNumber: "T1150", description: "Motor Mount Gasket", price: 9.99, quantity: 1 },
  { id: "ma-23", group: "Motor Assembly", name: "Complete Motor ASM", partNumber: "T1140", description: "Complete Motor ASM, Boxed", price: 299.99, quantity: 1 },

  // Hose & Wand Assembly Group
  { id: "hw-1", group: "Hose & Wand Assembly", name: "Hose Coupling Kit", partNumber: "T1059K", description: "Hose Coupling Kit", price: 29.99, quantity: 1 },
  { id: "hw-2", group: "Hose & Wand Assembly", name: "Coupling Magnet", partNumber: "T1060B", description: "Coupling Magnet (Bagged 20)", price: 19.99, quantity: 20 },
  { id: "hw-3", group: "Hose & Wand Assembly", name: "Grip Latch Spring", partNumber: "T1061B", description: "Spring, Grip Latch (Bagged 100)", price: 9.99, quantity: 100 },
  { id: "hw-4", group: "Hose & Wand Assembly", name: "Grip Latch", partNumber: "T1062", description: "Grip Latch", price: 14.99, quantity: 1 },
  { id: "hw-5", group: "Hose & Wand Assembly", name: "Hose Handle Kit", partNumber: "T1063K", description: "Hose Handle Kit", price: 34.99, quantity: 1 },
  { id: "hw-6", group: "Hose & Wand Assembly", name: "Handle Harness ASM", partNumber: "T1064", description: "Handle Harness ASM", price: 29.99, quantity: 1 },
  { id: "hw-7", group: "Hose & Wand Assembly", name: "Handle Wand", partNumber: "T1065", description: "Wand, Handle", price: 39.99, quantity: 1 },
  { id: "hw-8", group: "Hose & Wand Assembly", name: "Latch Button", partNumber: "R12587B", description: "Latch Button, C-Type, E2 (Bagged 30)", price: 14.99, quantity: 30 },
  { id: "hw-9", group: "Hose & Wand Assembly", name: "Trigger", partNumber: "T1067B", description: "Trigger (Bagged 10)", price: 12.99, quantity: 10 },
  { id: "hw-10", group: "Hose & Wand Assembly", name: "Handle Screw", partNumber: "T1068B", description: "Screw, Handle (Bagged 100)", price: 7.99, quantity: 100 },
  { id: "hw-11", group: "Hose & Wand Assembly", name: "Hose Carcass ASM", partNumber: "T1069", description: "Hose Carcass ASM", price: 49.99, quantity: 1 },
  { id: "hw-12", group: "Hose & Wand Assembly", name: "SD Wand", partNumber: "T1093", description: "Wand, SD, S/S, 16.75", price: 44.99, quantity: 1 },
  { id: "hw-13", group: "Hose & Wand Assembly", name: "Wand End Cap", partNumber: "T1094B", description: "Wand, End Cap (Bagged 5)", price: 9.99, quantity: 5 },
  { id: "hw-14", group: "Hose & Wand Assembly", name: "Wand Sleeve", partNumber: "T1096", description: "Wand, Sleeve", price: 14.99, quantity: 1 },
  { id: "hw-15", group: "Hose & Wand Assembly", name: "Wand Cable ASM", partNumber: "T1097", description: "Wand, Cable ASM", price: 24.99, quantity: 1 },
  { id: "hw-16", group: "Hose & Wand Assembly", name: "Long Wand ASM", partNumber: "T1143", description: "Wand ASM, Long", price: 54.99, quantity: 1 },
  { id: "hw-17", group: "Hose & Wand Assembly", name: "Complete Hose ASM", partNumber: "T1148", description: "Complete Hose ASM - Service", price: 129.99, quantity: 1 },
  { id: "hw-18", group: "Hose & Wand Assembly", name: "Switch NC", partNumber: "R13210", description: "Switch, Normally Closed", price: 19.99, quantity: 1 }
]